<?php

namespace ContainerWzGS8iH;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_GQlaF_2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.gQlaF.2' shared service.
     *
     * @return \App\Controller\UserPasswordEncoderInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\SecurityController::apiAdminLogin()": the $encoder argument is type-hinted with the non-existent class or interface: "App\\Controller\\UserPasswordEncoderInterface". Did you forget to add a use statement?');
    }
}
