<?php

namespace ContainerKuMBIx0;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Cmy3rqDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cmy3rqD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cmy3rqD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AccueilShopController::index' => ['privates', '.service_locator.6XxFdB9', 'get_ServiceLocator_6XxFdB9Service', true],
            'App\\Controller\\AccueilShopController::produitDetail' => ['privates', '.service_locator.iGUm1r8', 'get_ServiceLocator_IGUm1r8Service', true],
            'App\\Controller\\PanierController::validerCommande' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\SecurityController::apiLogin' => ['privates', '.service_locator.RAsJug5', 'get_ServiceLocator_RAsJug5Service', true],
            'App\\Controller\\SecurityController::inscription' => ['privates', '.service_locator.wU7gDXT', 'get_ServiceLocator_WU7gDXTService', true],
            'App\\Controller\\SecurityController::modifierStock' => ['privates', '.service_locator.Vq5yBlp', 'get_ServiceLocator_Vq5yBlpService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\AccueilShopController:index' => ['privates', '.service_locator.6XxFdB9', 'get_ServiceLocator_6XxFdB9Service', true],
            'App\\Controller\\AccueilShopController:produitDetail' => ['privates', '.service_locator.iGUm1r8', 'get_ServiceLocator_IGUm1r8Service', true],
            'App\\Controller\\PanierController:validerCommande' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\SecurityController:apiLogin' => ['privates', '.service_locator.RAsJug5', 'get_ServiceLocator_RAsJug5Service', true],
            'App\\Controller\\SecurityController:inscription' => ['privates', '.service_locator.wU7gDXT', 'get_ServiceLocator_WU7gDXTService', true],
            'App\\Controller\\SecurityController:modifierStock' => ['privates', '.service_locator.Vq5yBlp', 'get_ServiceLocator_Vq5yBlpService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\AccueilShopController::index' => '?',
            'App\\Controller\\AccueilShopController::produitDetail' => '?',
            'App\\Controller\\PanierController::validerCommande' => '?',
            'App\\Controller\\SecurityController::apiLogin' => '?',
            'App\\Controller\\SecurityController::inscription' => '?',
            'App\\Controller\\SecurityController::modifierStock' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AccueilShopController:index' => '?',
            'App\\Controller\\AccueilShopController:produitDetail' => '?',
            'App\\Controller\\PanierController:validerCommande' => '?',
            'App\\Controller\\SecurityController:apiLogin' => '?',
            'App\\Controller\\SecurityController:inscription' => '?',
            'App\\Controller\\SecurityController:modifierStock' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
