<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container60Yn13K\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container60Yn13K/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container60Yn13K.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container60Yn13K\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container60Yn13K\App_KernelDevDebugContainer([
    'container.build_hash' => '60Yn13K',
    'container.build_id' => '7261dbc7',
    'container.build_time' => 1682161548,
], __DIR__.\DIRECTORY_SEPARATOR.'Container60Yn13K');
