<?php

namespace ContainerLr7HBkX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosRest_Serializer_SymfonyService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'fos_rest.serializer.symfony' shared service.
     *
     * @return \FOS\RestBundle\Serializer\SymfonySerializerAdapter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'friendsofsymfony'.\DIRECTORY_SEPARATOR.'rest-bundle'.\DIRECTORY_SEPARATOR.'Serializer'.\DIRECTORY_SEPARATOR.'Serializer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'friendsofsymfony'.\DIRECTORY_SEPARATOR.'rest-bundle'.\DIRECTORY_SEPARATOR.'Serializer'.\DIRECTORY_SEPARATOR.'SymfonySerializerAdapter.php';

        return $container->privates['fos_rest.serializer.symfony'] = new \FOS\RestBundle\Serializer\SymfonySerializerAdapter(($container->privates['serializer'] ?? $container->load('getSerializerService')));
    }
}
