<?php

namespace ContainerBRcw3RX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SG4AWsUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sG4AWsU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sG4AWsU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'session' => ['privates', '.errored.8LQi49u', NULL, 'Cannot determine controller argument for "App\\Controller\\SecurityController::logout()": the $session argument is type-hinted with the non-existent class or interface: "App\\Controller\\SessionInterface". Did you forget to add a use statement?'],
        ], [
            'session' => '?',
        ]);
    }
}
