<?php

namespace ContainerQG7BY6R;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V0A2_QOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.v0A2.QO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.v0A2.QO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commandeService' => ['privates', 'App\\Service\\CommandeService', 'getCommandeServiceService', true],
        ], [
            'commandeService' => 'App\\Service\\CommandeService',
        ]);
    }
}
