<?php

namespace ContainerQG7BY6R;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandeServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\CommandeService' shared autowired service.
     *
     * @return \App\Service\CommandeService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CommandeService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->privates['App\\Service\\CommandeService'])) {
            return $container->privates['App\\Service\\CommandeService'];
        }

        return $container->privates['App\\Service\\CommandeService'] = new \App\Service\CommandeService($a);
    }
}
