<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLr7HBkX\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLr7HBkX/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerLr7HBkX.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerLr7HBkX\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerLr7HBkX\App_KernelTestDebugContainer([
    'container.build_hash' => 'Lr7HBkX',
    'container.build_id' => 'd49068fe',
    'container.build_time' => 1684587610,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLr7HBkX');
