<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVWmhhGe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVWmhhGe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVWmhhGe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVWmhhGe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVWmhhGe\App_KernelDevDebugContainer([
    'container.build_hash' => 'VWmhhGe',
    'container.build_id' => '7c3f226a',
    'container.build_time' => 1682674137,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVWmhhGe');
